parameters:
    env(DATABASE_URL): ''

doctrine:
    dbal:
        driver: pdo_sqlite
        charset: UTF8
        path: "%kernel.project_dir%/var/database.db"
    orm:
        auto_generate_proxy_classes: '%kernel.debug%'
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: false
        mappings:
            sample:
                type: xml
                dir: '%kernel.project_dir%/config/doctrine'
                prefix: Sample\Domain\Model
                is_bundle: false
