nelmio_api_doc:
    documentation:
        info:
            title: Sample App
            description: Sample DDD application.
            version: 1.0.0
    areas:
        path_patterns:
            - ^/api(?!/doc$)
