parameters:
    locale: 'en'

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    # Controller

    App\Controller\:
        resource: '../src/Controller'
        tags: [ controller.service_arguments ]

    # Serializer

    app.normalizer.author_id:
        class: Damax\Common\Bridge\Symfony\Serializer\EntityIdNormalizer
        arguments: [ 'App\Domain\Model\AuthorId' ]
        tags: [ serializer.normalizer ]

    app.normalizer.book_id:
        class: Damax\Common\Bridge\Symfony\Serializer\EntityIdNormalizer
        arguments: [ 'App\Domain\Model\BookId' ]
        tags: [ serializer.normalizer ]

    # Doctrine

    App\Doctrine\Orm\:
        resource: '../src/Doctrine/Orm'

    App\Doctrine\DataFixtures\:
        resource: '../src/Doctrine/DataFixtures'
        tags: [ doctrine.fixture.orm ]

    # Application

    App\Application\Service\:
        resource: '../src/Application/Service'

    App\Application\Dto\Assembler: ~

    # Domain

    App\Domain\Model\AuthorRepository: '@App\Doctrine\Orm\AuthorRepository'
    App\Domain\Model\BookRepository:   '@App\Doctrine\Orm\BookRepository'

    App\Domain\Model\IdGenerator:
        class: App\RamseyUuid\UuidIdGenerator

    App\Domain\Listener\AuthorListener:
        public: true
        tags:
            - { name: asynchronous_event_subscriber, subscribes_to: App\Domain\Event\BookCreated, method: onBookCreated }
